# Path to your oh-my-zsh installation.
export ZSH="/Users/nchen/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(zsh-completions zsh-autosuggestions git history-substring-search extract vi-mode zsh-syntax-highlighting) 

source $ZSH/oh-my-zsh.sh

# User configuration

[ -f ~/.env.sh ] && source ~/.env.sh
